feat(whoami): support GCP country header
mdn/rumba pull request #168
Opened 2023-03-23 16:42 UTC by caugner

2023-03-23 18:34 UTC, LeoMcA requested changes
Bit of a problem, `X-Appengine-Country` is a two letter country code:

> Country from which the request originated, as an [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) country code.

https://cloud.google.com/appengine/docs/standard/reference/request-headers?tab=node.js#app_engine-specific_headers

So those tests should be changed from `"X-Appengine-Country", "Iceland"` to `"X-Appengine-Country", "IS"`, which breaks some stuff.

And we sure we even get this header, aren't we running in GKE - are AppEngine headers set there too?

2023-03-24 10:01 UTC, fiji-flo requested changes
Looking good. Some suggestions to be more rusty 🦀 

Changing the Cargo.lock and removing the `countries.rs` isn't part of the suggestions and should be done locally.

2023-03-24 10:13 UTC, caugner commented on src/api/whoami.rs
> +        .unwrap_or(String::from("Unknown"));
Resolved via d128156.

2023-03-24 10:13 UTC, caugner commented on src/util/mod.rs
> +}
Resolved via d128156.

2023-03-24 10:13 UTC, caugner commented on Cargo.toml
> +phf = { version = "0.11.1", features = ["macros"] }
Resolved via d128156.

2023-03-24 11:19 UTC, fiji-flo approved these changes
👍

2023-03-24 13:20 UTC, merged